version: '3.4'
services:
  mongo-build:
    build: 
      context: ./buildmongo #from custom Dockerfile
    ports:
      - "27017:27017" # bind local port 27018 to container port 27017 so it's not occupied
    #command: mongod --dbpath /data/db #--shutdown && exit 0 # Build and persist the DB then exit

  mongo-readonly:
    image: mongo #from Docker
    restart: always
    networks:
      - app-tier
   # volumes:
   #   - ./data:/data/db #Mount the /data/db directory on the host machine to persist data
    ports:
      - "27018:27017" #default mongodb port
    depends_on:
      - mongo-build

  app:
    build: ./app #from custom Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongo-readonly  
      - mongo-build
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge


volumes:
  db-data:

