apiVersion: v1
kind: Pod
metadata:
  name: check-volume
spec:
  containers:
  - name: volume-checker
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: bw-db
      mountPath: /data
  volumes:
  - name: bw-db
    persistentVolumeClaim:
      claimName: index-pvc
  restartPolicy: Never
